### ISSUE TITLE
"Application not found"

### ISSUE THREAD

**Issue by drsaunders** [dexplo/jupyter_to_medium#23] opened 2020-11-21 14:34 UTC
Deploying from within a Jupyter notebook, I get this after I hit publish:

```Failed to post to Medium

Returned error message below

"ValueError: Problem authenticating author:
{\"errors\":[{\"message\":\"Application not found\",\"code\":6005}]}

Traceback (most recent call last):
File \"/Users/dsaunder/pokeslots/venvs/pokeslots/lib/python3.8/site-packages/jupyter_to_medium/_publish_to_medium.py\", line 96, in get_author_id
return r.json()['data']['id']
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File \"/Users/dsaunder/pokeslots/venvs/pokeslots/lib/python3.8/site-packages/jupyter_to_medium/_bundler.py\", line 37, in upload
data = publish(**kwargs)
File \"/Users/dsaunder/pokeslots/venvs/pokeslots/lib/python3.8/site-packages/jupyter_to_medium/_publish_to_medium.py\", line 300, in publish
p.main()
File \"/Users/dsaunder/pokeslots/venvs/pokeslots/lib/python3.8/site-packages/jupyter_to_medium/_publish_to_medium.py\", line 216, in main
self.author_id = self.get_author_id()
File \"/Users/dsaunder/pokeslots/venvs/pokeslots/lib/python3.8/site-packages/jupyter_to_medium/_publish_to_medium.py\", line 98, in get_author_id
raise ValueError('Problem authenticating author: \\n' + r.text)
ValueError: Problem authenticating author:
{\"errors\":[{\"message\":\"Application not found\",\"code\":6005}]}
"
```

I get it whether I use the `.jupyter_to_medium/integration_token` or enter the token manually. Information of possible relevance is that I have a profile picture, bio and 1 post up already, and that this URL https://medium.com/me/applications gives me "You don’t have access to this page."

**Comment by gethgle** [comment] 2020-12-04 21:46
I got the same error when running python code. this code 
import jupyter_to_medium as jtm
jtm.publish('My Awesome Jupyter Notebook.ipynb',
            integration_token=None,
            pub_name=None,
            title=None,
            tags=None,
            publish_status='draft',
            notify_followers=False,
            license='all-rights-reserved',
            canonical_url=None,
            chrome_path=None,
            save_markdown=False,
            table_conversion='chrome'
            )
and also used the first method I got this error 

Failed to post to Medium
Returned error message below

"FileNotFoundError: [Errno 2] No such file or directory: 'Downloads\\\\file name'

Traceback (most recent call last):
File \"C:\\Users\\shankar\\anaconda3\\lib\\site-packages\\nbformat\\__init__.py\", line 138, in read
buf = fp.read()
AttributeError: 'WindowsPath' object has no attribute 'read'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File \"C:\\Users\\shankar\\anaconda3\\lib\\site-packages\\jupyter_to_medium\\_bundler.py\", line 37, in upload
data = publish(**kwargs)
File \"C:\\Users\\shankar\\anaconda3\\lib\\site-packages\\jupyter_to_medium\\_publish_to_medium.py\", line 297, in publish
p = Publish(filename, integration_token, pub_name, title, tags,
File \"C:\\Users\\shankar\\anaconda3\\lib\\site-packages\\jupyter_to_medium\\_publish_to_medium.py\", line 41, in __init__
self.nb = self.get_notebook()
File \"C:\\Users\\shankar\\anaconda3\\lib\\site-packages\\jupyter_to_medium\\_publish_to_medium.py\", line 76, in get_notebook
return nbformat.read(self.filename, as_version=4)
File \"C:\\Users\\shankar\\anaconda3\\lib\\site-packages\\nbformat\\__init__.py\", line 140, in read
with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Downloads\\\\ file name'
"
I am not able to understand where the problem is ...

**Comment by Rukshar-Alam** [comment] 2021-09-08 06:52
> I got the same error when running python code. this code
> import jupyter_to_medium as jtm
> jtm.publish('My Awesome Jupyter Notebook.ipynb',
> integration_token=None,
> pub_name=None,
> title=None,
> tags=None,
> publish_status='draft',
> notify_followers=False,
> license='all-rights-reserved',
> canonical_url=None,
> chrome_path=None,
> save_markdown=False,
> table_conversion='chrome'
> )
> and also used the first method I got this error
> 
> Failed to post to Medium
> Returned error message below
> 
> "FileNotFoundError: [Errno 2] No such file or directory: 'Downloads\\file name'
> 
> Traceback (most recent call last):
> File "C:\Users\shankar\anaconda3\lib\site-packages\nbformat\**init**.py", line 138, in read
> buf = fp.read()
> AttributeError: 'WindowsPath' object has no attribute 'read'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\shankar\anaconda3\lib\site-packages\jupyter_to_medium\_bundler.py", line 37, in upload
> data = publish(**kwargs)
> File "C:\Users\shankar\anaconda3\lib\site-packages\jupyter_to_medium\_publish_to_medium.py", line 297, in publish
> p = Publish(filename, integration_token, pub_name, title, tags,
> File "C:\Users\shankar\anaconda3\lib\site-packages\jupyter_to_medium\_publish_to_medium.py", line 41, in **init**
> self.nb = self.get_notebook()
> File "C:\Users\shankar\anaconda3\lib\site-packages\jupyter_to_medium\_publish_to_medium.py", line 76, in get_notebook
> return nbformat.read(self.filename, as_version=4)
> File "C:\Users\shankar\anaconda3\lib\site-packages\nbformat\**init**.py", line 140, in read
> with io.open(fp, encoding='utf-8') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'Downloads\\ file name'
> "
> I am not able to understand where the problem is ...

I have the same problem. Have you found a solution?

**Comment by mjam03** [comment] 2021-11-11 13:33
Hi,

Appreciate this is a long time after you logged the issue but if you are still experiencing it / having issues I think the easiest way to check would be if you could check and return the results of the following for me:

```python
from pathlib import Path
import requests

# function to fetch token from local storage location
def get_integration_token(it):
    if not it:
        it_path = Path.home() / '.jupyter_to_medium' / 'integration_token'
        it = open(it_path).read().splitlines()[0]
    return it

# set params to make request
url = "https://api.medium.com/v1/me"
int_token = get_integration_token(None)
# this is where the int token gets passed so this is author specific
headers = {
    'Host': 'api.medium.com',
    'Authorization': 'Bearer {}'.format(int_token),
    'Accept': 'application/json',
    'Accept-Charset': 'utf-8'
}
# should get a json response with your author data that is then used to publish
r = requests.get(url, headers=headers)
r.status_code
r.content
```

This is what is going on under the hood where the `get_integration_token` function is then omitted if you pass a valid token in the html page. Let me know otherwise I'll close the issue as I don't see any problems for me - either when I run both attempts myself, nor in the code.

**Comment by mjam03** [comment] 2021-11-19 12:28
Going to close the issue. Let me know if you are still seeing the above problems and get a chance to run the above code. If so I'll happily reopen the issue and take a look.

**Closed by mjam03** 2021-11-19 12:28 UTC
